### PR TITLE
TypeError customize.sh

### PR DESCRIPTION
**Pull request by ozingi**
NUM=29
if [ "$API" -lt $NUM ]
The value type is inconsistent

### CODE REVIEW

**Comment by reiryuki** [comment]
There is no mistake
The result will be the same in this case if you put "$API" or $API

**Comment by taoaoooo** [comment]
This is wrong, keep it that way you need to change $UNM to "$UNM" as well

**Comment by ozingi** [comment]
> There is no mistake The result will be the same in this case if you put "$API" or $API
I've tested it
This is wrong, keep it that way you need to change $UNM to "$UNM" as well

**Comment by reiryuki** [comment]
Screenshot_20220502-125247_Material Terminal
Maybe you don't understand buddy, keep learning 👍..

**Comment by ozingi** [comment]
> Screenshot_20220502-125247_Material Terminal Maybe you don't understand buddy, keep learning 👍..

I made a mistake. Thank you for correcting me ❤️

**Pull request closed without merging**
